---
name: CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - name: Put current date into a variable
      run: |
        NOW=$(date +'%Y-%m-%d')
        echo "NOW=$NOW" >> $GITHUB_ENV

    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5 # v3.1.0

    - name: Make gradlew executable
      run: chmod +x ./gradlew

    - name: Build with Gradle Wrapper
      run: ./gradlew clean build

    - name: Build Docker image
      run: docker build -t seirios86/discovery-service:${{ env.NOW }} .

    - name: Login to Docker Hub
      run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Push Docker image
      run: docker push seirios86/discovery-service:${{ env.NOW }}

  dependency-submission:

    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Generate and submit dependency graph
      uses: gradle/actions/dependency-submission@417ae3ccd767c252f5661f1ace9f835f9654f2b5 # v3.1.0

  deploy:

    runs-on: ubuntu-latest
    needs: [build, dependency-submission]

    steps:
    - name: Put current date into a variable
      run: |
        NOW=$(date +'%Y-%m-%d')
        echo "NOW=$NOW" >> $GITHUB_ENV

    - uses: actions/checkout@v4
    - name: Deploy to server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        script: |
          docker pull seirios86/discovery-service:${{ env.NOW }}
          docker stop discovery || true
          docker rm discovery || true
          docker run -d -p 8761:8761 -v ~/data:/app/data --network=card_payment --ip 172.18.0.2 --name=discovery seirios86/discovery-service:${{ env.NOW }}
